name: 'Docker Build and Push to Nova AI'
description: 'GitHub Action to push Docker images with custom authentication'
# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'cloud-lightning'
  color: 'green'
inputs:
  clientId:
    description: 'Client ID for authentication'
    required: true
  secret:
    description: 'Secret for authentication'
    required: true
  imageName:
    description: 'Docker image name'
    required: true
  imageTag:
    description: 'Docker image tag'
    required: true
  artifactId:
    description: 'Nova Artifact ID to associate with the image'
    required: true
  dockerfilePath:
    description: 'Path to the Dockerfile'
    required: false
  dockerfile:
    description: 'Inline Dockerfile content'
    required: false
outputs:
  location:
    description: 'Location of the uploaded Docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.clientId }}
    - ${{ inputs.secret }}
    - ${{ inputs.imageName }}
    - ${{ inputs.imageTag }}
    - ${{ inputs.artifactId }}
    - ${{ inputs.dockerfilePath }}
    - ${{ inputs.dockerfile }}
